### ISSUE TITLE
Auto Builder does not detect local maven install, fails to download maven automatically

### ISSUE THREAD

**Issue by bhjelmar** [Appdynamics/AutoBuilder#1]
Hey! Cool tool. It looks like it tries to download maven though without checking if there is a local install first. Logs below.

$ java -jar AutoBuilder-22.2.1.jar 

Enter Path (Should be an empty directory) :
tmp

Choose the extension you want to build:

1. URL Monitoring Extension
2. Process Monitoring Extension
3. Log Monitoring Extension
4. File Watcher Monitoring Extension
5. ActiveMQ Monitoring Extension
6. DataPower Monitoring Extension
7. RabbitMQ Monitoring Extension
8. Apache Monitoring Extension
9. Redis Monitoring Extension
10. Hadoop Monitoring Extension
11. Linux Monitoring Extension
12. SQL Monitoring Extension
13. F5 Monitoring Extension
14. NGINX Monitoring Extension
15. Zookeeper Monitoring Extension
16. HA Proxy Monitoring Extension
17. Kafka Monitoring Extension
18. ElasticSearch Monitoring Extension
19. SSL Certificate Monitoring Extension
20. Azure Monitoring Extension
21. VMware vSphere Monitoring Extension
22. Apache Spark Monitoring Extension
23. Docker Monitoring Extension
24. JMX Monitoring Extension
25. AWS EC2 Monitoring Extension
26. AWS Lambda Monitoring Extension
27. AWS RDS Monitoring Extension
28. AWS S3 Monitoring Extension
29. AWS SQS Monitoring Extension
30. AWS Custom Namespace Monitoring Extension

12

(Step 1/5) Cloning Git repository...

Git repository cloned successfully!

(Step 2/5) Downloading Apache Maven...
Unable to download Apache Maven!

**Comment by bhjelmar** [comment]
I dio have maven installed locally, ideally the tool could auto-find the install

$ mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.076 s
[INFO] Finished at: 2022-04-08T13:49:13-04:00

**Comment by jpanchma** [comment]
Hi @bhjelmar, Thanks for your inputs. The error "Unable to download Apache Maven!" has been fixed in the latest version (AutoBuilder-22.6.0). 
Regarding the scan for local maven, it seem to be a tedious process as the version of apache maven might sometimes be incompatible and there is no list of specific versions that are supported. Hence, downloading maven seems to be a better way without any hiccups as we always tend to download the version we want! 
Additionally, there could be bunch of different problems like user permission issues with the pre-installed maven directory in the customer's environment.
